steps:
- name: 'ubuntu'
  args: ['ls', '-l', '/workspace/']

- name: 'ubuntu'
  volumes:
  - name: 'vol1'
    path: '/persistent_volume'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
        echo "Hello, world! ${_PRJ} ${_UIPORT}" > /persistent_volume/file
        no_failure_count=`cat /persistent_volume/file| grep -o "443" | wc -l`
        echo "no_failure_count for 443 is $no_failure_count"

        if [ "$no_failure_count" -ge 1 ]; then 
        exit 0; 
        else 
        exit 255; 
        fi
- name: 'ubuntu'
  volumes:
  - name: 'vol1'
    path: '/persistent_volume'
  args: ['cat', '/persistent_volume/file']
  
- name: maven:3.6-jdk-8
  entrypoint: mvn
  args: ['clean', 'verify', '-Dusers=1', '-DrampUP=2', '-DloopCnt=2', '-DUIHOST=${_UIHOST}', '-DUIPORT=${_UIPORT}']

- name: 'ubuntu'
  args: ['ls', '-l', '/workspace/']

substitutions:
    _PRJ: "v6.9.1"
    _UIPORT: "443"
    _UIHOST: "reqres.in"

artifacts:
  objects:
    location: 'gs://skc_bkt_1/perf_res2'
    paths: ['target/jmeter/results/*.*'] 

